import { Geist, Geist_Mono } from "next/font/google";
export const metadata = {
  title: "Tools & Skiils",
  description: "Generated by create next app",
};
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>   
          {children}              
      </body>
    </html>
  );
}
